name: CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: nake all
      - uses: softprops/action-gh-release@v1
        with:
          files: dist/terraspanner
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
